version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:14
    environment:
      POSTGRES_DB: lnbits_db
      POSTGRES_USER: lnbits
      POSTGRES_PASSWORD: secret
      PGDATA: /data/postgres
    volumes:
       - ./data/postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped